title: NewRock Wireless | Premium Electronics
url: "https://drutech6.github.io"
baseurl: "/newrock-wireless-1st"

defaults:
  - scope:
      path: "_layouts/default.html"
    values:
      layout: "default"
